version: '2'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ${CONFIG_DIR}:/config
      - ${CUSTOM_COMPONENTS_DIR}:/config/custom_components
    environment:
      TZ: ${TZ}
    {{- if or (.Values.DEV_ZWAVE) (.Values.DEV_RFXCOM) }}
    devices:
      {{- if (.Values.DEV_ZWAVE) }}
      - ${DEV_ZWAVE}:/zwaveusb:rwm
      {{- end }}
      {{- if (.Values.DEV_RFXCOM) }}
      - ${DEV_RFXCOM}:/rfxtrxusb:rwm
      {{- end }}
    {{- end }}
    restart: always
    network_mode: host
    user: 1100:1100
