version: '2'

.catalog:
  name: Home Assistant
  description: |
    Track and control all devices at home and automate control.
  version: Latest Stable
  questions:
   - variable: 'CONFIG_DIR'
     description: 'Location of the persistant data storage'
     label: 'Config Directory'
     required: true
     type: 'string'
     default: '/home/rancher/docker/homeassistant'
   - variable: 'CUSTOM_COMPONENTS_DIR'
     description: 'Location of the custom components folder'
     label: 'Custom Components Directory'
     required: true
     type: 'string'
     default: '/home/rancher/docker/homeassistant/custom_components'
   - variable: 'TZ'
     description: 'Timezone (eg. America/New_York)'
     label: 'Timezone'
     required: true
     type: 'string'
     default: 'America/New_York'
   - variable: 'DEV_ZWAVE'
     description: 'Device (/dev/...), leave empty for no ZWave device'
     label: 'ZWave device'
     required: false
     type: 'string'
