version: '2'
services:
  deconz:
    container_name: deCONZ
    image: marthoc/deconz:latest
    volumes:
      - ${CONFIG_DIR}:/root/.local/share/dresden-elektronik/deCONZ
    ports:
      - ${DECONZ_WEB_PORT}:80
      - ${DECONZ_WS_PORT}:443
    environment:
      TZ: ${TZ}
      DECONZ_UPNP: ${DECONZ_UPNP}
      DECONZ_DEVICE: /dev/ttyACM0
      DECONZ_WEB_PORT: ${DECONZ_WEB_PORT}
      DECONZ_WS_PORT: ${DECONZ_WS_PORT}
      DECONZ_VNC_MODE: ${DECONZ_VNC_MODE}
      DECONZ_VNC_PORT: ${DECONZ_VNC_PORT}
      DECONZ_VNC_PASSWORD: ${DECONZ_VNC_PASSWORD}
    {{- if (.Values.DEV_ZIGBEE) }}
    devices:
      {{- if (.Values.DEV_ZIGBEE) }}
      - ${DEV_ZIGBEE}:/dev/ttyACM0:rwm
      {{- end }}
    {{- end }}
    restart: unless-stopped
