name: Node-RED
description: |
  A flow-based development tool for visual programming developed for wiring together hardware devices, APIs and online services.
version: Latest Stable
category: Automation
